services:
  laravel:
    build: ./Laravel
    container_name: macuin_laravel
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/public/build
    networks:
      - macuin_network

  flask:
    build: ./Flask
    container_name: server_flask
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - macuin_network

  api:
    build: ./miAPI
    container_name: server_api
    ports:
      - "8080:8080"
    volumes:
      - ./miAPI:/app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:123456@postgres:5432/DB_MACUIN
    networks:
      - macuin_network

  postgres:
    image: postgres:15
    container_name: macuin_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DB_MACUIN
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d DB_MACUIN"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - macuin_network

networks:
  macuin_network:
    driver: bridge

volumes:
  postgres_data: