services:
  laravel:
    build: ./Laravel
    container_name: macuin_laravel
    ports:
      - "8000:80"
    volumes:
      - ./Laravel:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/public/build

  flask:
    build: ./Flask
    container_name: server_flask
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    environment:
      - FLASK_DEBUG=1